:_module-type: CONCEPT
[id="the-location-of-tuned-profiles_{context}"]
= The location of TuneD profiles

[role="_abstract"]
*TuneD* stores profiles in the following directories:

[filename]`{system-profile-dir}`::
Distribution-specific profiles are stored in the [filename]`{system-profile-dir}` directory. Each profile has its own directory. The profile consists of the main configuration file called `tuned.conf`, and optionally other files, for example helper scripts.

[filename]`{user-profile-dir}`::
If you need to customize a profile, copy the profile directory into the [filename]`{user-profile-dir}` directory, which is used for custom profiles, and then adjust it. If there is a system profile and a custom profile of the same name, the custom profile located in [filename]`{user-profile-dir}` is used.

.User-defined profile directories
====
If you want to make TuneD load profiles from a directory other than [filename]`{system-profile-dir}` and [filename]`{user-profile-dir}`, you can list it in [filename]`/etc/tuned/tuned-main.conf` as follows:
[subs="attributes"]
----
profile_dirs={system-profile-dir},{user-profile-dir},/my/custom/profiles
----
In this example, profiles are loaded also from [filename]`/my/custom/profiles`. If two directories contain profiles with the same names, the one that is listed later takes precedence.
====

[role="_additional-resources"]
.Additional resources
* `tuned.conf(5)` man page.
