:_module-type: PROCEDURE
[id="creating-new-tuned-profiles_{context}"]
= Creating new TuneD profiles

[role="_abstract"]
This procedure creates a new *TuneD* profile with custom performance rules.

.Prerequisites

ifndef::pantheonenv[]
* The `tuned` service is running. See xref:installing-and-enabling-tuned_getting-started-with-tuned[Installing and Enabling Tuned] for details.
endif::[]

ifdef::pantheonenv[]
* The `tuned` service is running. See xref:modules/performance/proc_installing-and-enabling-tuned.adoc[Installing and Enabling Tuned] for details.
endif::[]

.Procedure

. In the [filename]`{user-profile-dir}` directory, create a new directory named the same as the profile that you want to create:
+
[subs="attributes, quotes"]
----
# mkdir {user-profile-dir}/[replaceable]_my-profile_
----

. In the new directory, create a file named [filename]`tuned.conf`. Add a `[main]` section and plug-in definitions in it, according to your requirements.
+
For example, see the configuration of the `balanced` profile:
+
----
[main]
summary=General non-specialized TuneD profile

[cpu]
governor=conservative
energy_perf_bias=normal

[audio]
timeout=10

[video]
radeon_powersave=dpm-balanced, auto

[scsi_host]
alpm=medium_power
----

. To activate the profile, use:
+
[subs="quotes"]
----
# tuned-adm profile [replaceable]_my-profile_
----

. Verify that the *TuneD* profile is active and the system settings are applied:
+
[subs="quotes"]
----
$ tuned-adm active

Current active profile: [replaceable]_my-profile_
----
+
----
$ tuned-adm verify

Verification succeeded, current system settings match the preset profile.
See TuneD log file ('/var/log/tuned/tuned.log') for details.
----

[role="_additional-resources"]
.Additional resources
* `tuned.conf(5)` man page
