:_module-type: PROCEDURE
[id="setting-a-tuned-profile_{context}"]
= Setting a TuneD profile

[role="_abstract"]
This procedure activates a selected *TuneD* profile on your system.

.Prerequisites

ifndef::pantheonenv[]
* The `tuned` service is running. See xref:installing-and-enabling-tuned_getting-started-with-tuned[Installing and Enabling Tuned] for details.
endif::[]

ifdef::pantheonenv[]
* The `tuned` service is running. See xref:modules/performance/proc_installing-and-enabling-tuned.adoc[Installing and Enabling Tuned] for details.
endif::[]

.Procedure

. Optionally, you can let *TuneD* recommend the most suitable profile for your system:
+
[subs="quotes"]
----
# tuned-adm recommend

[replaceable]_balanced_
----

. Activate a profile:
+
[subs="quotes"]
----
# tuned-adm profile [replaceable]_selected-profile_
----
+
Alternatively, you can activate a combination of multiple profiles:
+
[subs="quotes"]
----
# tuned-adm profile [replaceable]_profile1_ [replaceable]_profile2_
----
+
.A virtual machine optimized for low power consumption
====
The following example optimizes the system to run in a virtual machine with the best performance and concurrently tunes it for low power consumption, while the low power consumption is the priority:

----
# tuned-adm profile virtual-guest powersave
----
====

. View the current active *TuneD* profile on your system:
+
[subs="quotes"]
----
# tuned-adm active

Current active profile: [replaceable]_selected-profile_
----

. Reboot the system:
+
----
# reboot
----

.Verification steps

* Verify that the *TuneD* profile is active and applied:
+
----
$ tuned-adm verify

Verification succeeded, current system settings match the preset profile.
See TuneD log file ('/var/log/tuned/tuned.log') for details.
----


[role="_additional-resources"]
.Additional resources
* `tuned-adm(8)` man page
