.\"/* 
.\" * All rights reserved
.\" * Copyright (C) 2015-2017 Red Hat, Inc.
.\" * Authors: Jaroslav Škarvada
.\" *
.\" * This program is free software; you can redistribute it and/or
.\" * modify it under the terms of the GNU General Public License
.\" * as published by the Free Software Foundation; either version 2
.\" * of the License, or (at your option) any later version.
.\" *
.\" * This program is distributed in the hope that it will be useful,
.\" * but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" * GNU General Public License for more details.
.\" *
.\" * You should have received a copy of the GNU General Public License
.\" * along with this program; if not, write to the Free Software
.\" * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
.\" */
.\" 
.TH TUNED_PROFILES_CPU_PARTITIONING "7" "30 Mar 2017" "tuned"
.SH NAME
tuned\-profiles\-cpu\-partitioning - description of profile provided for for CPU partitioning

.SH DESCRIPTION
The profile is provided for CPU partitioning.

.SH PROFILES
The following profiles is provided:

.TP
.BI "cpu\-partitioning"
Profile optimized for CPU partitioning.

.SH "FILES"
.NF
.I /etc/tuned/*
.I /usr/lib/tuned/*

.SH "SEE ALSO"
.BR tuned (8)
.BR tuned\-adm (8)
.BR tuned\-profiles (7)
.BR tuned\-profiles\-atomic (7)
.BR tuned\-profiles\-sap (7)
.BR tuned\-profiles\-sap\-hana (7)
.BR tuned\-profiles\-oracle (7)
.BR tuned\-profiles\-realtime (7)
.BR tuned\-profiles\-nfv\-host (7)
.BR tuned\-profiles\-nfv\-guest (7)
.BR tuned\-profiles\-compat (7)
.SH AUTHOR
.NF
Jaroslav Škarvada <jskarvad@redhat.com>
