srpm_build_deps: []
upstream_tag_template: v{version}
jobs:
- job: copr_build
  trigger: pull_request
  targets:
  - fedora-all
  - epel-7-x86_64
  - epel-8-x86_64
  - centos-stream-9-x86_64
  - centos-stream-10-x86_64
- job: tests
  trigger: pull_request
  targets:
  - fedora-all
  - epel-7-x86_64
  - epel-8-x86_64
  - centos-stream-9-x86_64
  - centos-stream-10-x86_64

files_to_sync:
- tuned.spec
- .packit.yaml
