#!/usr/bin/python
#
# tuned: A simple daemon that performs monitoring and adaptive configuration
#        of devices in the system
#
# Copyright (C) 2008, 2009 Red Hat, Inc.
# Authors: Phil Knirsch
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#

import sys, os.path, getopt, atexit, signal
import logging, tuned_logging

log = logging.getLogger("tuned")

def usage():
	print "Usage: tuned [-d|--daemon] [-c conffile|--config=conffile] [-D|--debug]"

def handler(signum, frame):
	log.debug("Received signal number %d." % signum)
	sys.exit()

def daemonize():
	log.debug("Daemonizing")

	try:
		pid = os.fork()
		if pid > 0:
			sys.exit(0)
	except OSError, e:
		log.critical("Cannot fork: %s", str(e))
		sys.exit(1)

	os.chdir("/")
	os.setsid()
	os.umask(0)

	try:
		pid = os.fork()
		if pid > 0:
			sys.exit(0)
	except OSError, e:
		log.cricital("Cannot fork: %s", str(e))
		sys.exit(1)

	sys.stdout = sys.stderr = open("/dev/null", 'a+')

if __name__ == "__main__":
	try:
		opts, args = getopt.getopt(sys.argv[1:], "dc:D", ["daemon", "config=", "debug"])
	except getopt.error, e:
		print >>sys.stderr, ("Error parsing command-line arguments: %s", e)
		usage()
	        sys.exit(1)

	if len(args) > 0:
		print >>sys.stderr, ("Too many arguments.")
		usage()
		sys.exit(1)

	daemon = False
	cfgfile = "/etc/tuned.conf"
	debug = False
	for (opt, val) in opts:
		if   opt in ['-d', "--daemon"]:
			daemon = True
		elif opt in ['-c', "--config"]:
			cfgfile = val
		elif opt in ['-D', "--debug"]:
			debug = True

	TUNEDDIR = "/usr/share/tuned"
	if not TUNEDDIR in sys.path:
		sys.path.append(TUNEDDIR)

	from tuned import tuned

	tuned.init(TUNEDDIR, cfgfile, debug = debug)

	if daemon:
		daemonize()

	atexit.register(logging.shutdown)
	atexit.register(tuned.cleanup)
	signal.signal(signal.SIGTERM, handler)

	tuned.run()
	tuned.cleanup()
