.\"/* 
.\" * All rights reserved
.\" * Copyright (C) 2009-2014 Red Hat, Inc.
.\" * Authors: Marcela Mašláňová, Phil Knirsch, Jaroslav Škarvada
.\" *
.\" * This program is free software; you can redistribute it and/or
.\" * modify it under the terms of the GNU General Public License
.\" * as published by the Free Software Foundation; either version 2
.\" * of the License, or (at your option) any later version.
.\" *
.\" * This program is distributed in the hope that it will be useful,
.\" * but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" * GNU General Public License for more details.
.\" *
.\" * You should have received a copy of the GNU General Public License
.\" * along with this program; if not, write to the Free Software
.\" * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
.\" */
.\" 
.TH TUNED_ADM "1" "15 Oct 2014" "Linux Programmer's Manual"
.SH NAME
tuned\-adm - commandline tool for switching between different tuning profiles
.SH SYNOPSIS
.B tuned\-adm 
.B 
.BR [ " help ", " list ", " active ", " profile <profile> ", " off " ]
.br
.SH DESCRIPTION
This command line utility allows user to switch between user definable tuning profiles. Several predefined profiles are already included for some of the more common cases. Although the profiles typically refer to a common use case you can of course switch to any profile on any system. So switching to the laptop-battery-powersave profile on a server will activate this profile on it. This way, depending on your requirements you can select any of the profiles that fits your needs. You can even create your own profile, either based on one of the existing ones by copying it or make a completely new one. The profiles are stored in subdirectories below /etc/tune-profiles.

.SH "OPTIONS"

.SS
.TP
.B help
Print out the list of commands. It's also the default if you start tuned\-adm without any commands.

.TP
.B list
List all available profiles.

.TP
.B active
Show current active profile.

.TP
.B profile <profile>
Switches to the given profilename. If none is given or no valid one is given the command gracefully exits without performing any operation.

.TP
.B off
Switch off all ktune and tuned settings and remove them from services. The configuration file are set to previous settings.

.SH "FILES"
.nf
/etc/tune\-profiles/*

.SH "SEE ALSO"
.BR tuned (8)
.BR tuned\-profiles (7)
.BR tuned\-profiles\-sap (7)
.BR tuned\-profiles\-sap\-hana (7)
.SH AUTHOR
.NF
Marcela Mašláňová <mmaslano@redhat.com>
Phil Knirsch <pknirsch@redhat.com>
Jaroslav Škarvada <jskarvad@redhat.com>
