[id="creating-a-tuned-profile-from-powertop-suggestions_{context}"]
= Creating a Tuned profile from PowerTOP suggestions

The powertop2tuned utility is a tool that allows you to create custom tuned profiles from the PowerTOP suggestions.

[discrete]
== Prerequisites

*  To install the powertop2tuned application, run the following command as root:

yum install tuned-utils

[discrete]
== Procedure

To create a custom profile, run the following command as root:

powertop2tuned new_profile_name

By default it creates the profile in the /etc/tuned directory and it bases it on the currently selected tuned profile. For safety reasons all PowerTOP tunings are initially disabled in the new profile. To enable them uncomment the tunings of your interest in the /etc/tuned/profile/tuned.conf. You can use the --enable or -e option that will generate the new profile with most of the tunings suggested by PowerTOP enabled. Some dangerous tunings like the USB autosuspend will still be disabled. If you really need them you will have to uncomment them manually. By default, the new profile is not activated. To activate it run the following command:

tuned-adm profile new_profile_name

For a complete list of the options powertop2tuned supports, type in the following command:

powertop2tuned --help

[discrete]
== Additional resources

* A bulleted list of links to other material closely related to the contents of the procedure module.
* For more details on writing procedure modules, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
